name: Test-ItemMetaData
main: com.elmakers.mine.bukkit.plugins.test.TestItemMetaData
version: 1.0
website: http://mine.elmakers.com
author: NathanWolf
description : A plugin to unit test Bukkit-3221 and Bukkit-4767
commands:
  invpush:
    description: Save your current inventory
    usage: /invpush
  invpop:
    description: Return your current inventory
    usage: /invpop
  itemglow:
    description: Make the held item glow
    usage: /itemglow
  itemunglow:
    description: Remove held item glow
    usage: /itemunglow
  itemunenchant:
    description: Remove all enchants from held item
    usage: /itemunenchant
  itemcheck:
    description: Check the held item for glow and enchants
    usage: /itemcheck
  itemclone:
    description: Spawn a copy of the item in your hand
    usage: /itemclone
  itemfly:
    description: Make held item a magic flying wand
    usage: /itemfly
  itemunfly:
    description: Remove flying ability from held item
    usage: /itemunfly